services:
  lstid_detector:
    image: lstid_detector
    build: .
    container_name: lstid_detector_container
    volumes:
      - ./output:/output
      - ./raw_data:/raw_data
      - lstid_cache:/cache

volumes:
  lstid_cache: